[versions]
forge260102="26.1.2-64.1.0"
neo260102="26.1.2.94"
forge262000 = "26.2-65.1.0"
neo262000 = "26.2.0.48-beta"
# https://mvnrepository.com/artifact/org.scala-lang/scala-library
scala = "3.8.4"
# https://mvnrepository.com/artifact/org.typelevel/cats-core
cats = "2.13.0"
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
jupiter-api = "6.1.3"
# https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher
jupiter-platform = "6.1.3"
mockito-core = "5.23.0"
mockito-inline = "5.2.0"

plugin_cf = "4.0"
plugin_shadow = "9.6.1"
plugin_idea_ext = "1.4.1"
plugin_ghr = "2.5.2"
plugin_publish_all = "2.2.0"
plugin_forge_gradle = "7.0.31"
plugin_forge_jarjar = "0.2.3"
plugin_neoforge_moddev = "2.0.143"

[libraries]
scala = { group = "org.scala-lang", name = "scala-library", version.ref = "scala" }
scala3 = { group = "org.scala-lang", name = "scala3-library_3", version.ref = "scala" }
cats-kernel = { group = "org.typelevel", name = "cats-kernel_3", version.ref = "cats" }
cats-core = { group = "org.typelevel", name = "cats-core_3", version.ref = "cats" }
cats-free = { group = "org.typelevel", name = "cats-free_3", version.ref = "cats" }
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter-api" }
jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter-api" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter-api" }
jupiter-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "jupiter-platform" }
mockito_core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
mockito_inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito-inline" }
forge260102 = { group = "net.minecraftforge", name = "forge", version.ref = "forge260102" }
neo260102 = { group = "net.neoforged", name = "neoforge", version.ref = "neo260102" }
forge262000 = { group = "net.minecraftforge", name = "forge", version.ref = "forge262000" }
neo262000 = { group = "net.neoforged", name = "neoforge", version.ref = "neo262000" }

[plugins]
cf = { id = "com.kotori316.plugin.cf", version.ref = "plugin_cf" }
shadow = { id = "com.gradleup.shadow", version.ref = "plugin_shadow" }
idea = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin_idea_ext" }
ghr = { id = "com.github.breadmoirai.github-release", version.ref = "plugin_ghr" }
publish-all = { id = "me.modmuss50.mod-publish-plugin", version.ref = "plugin_publish_all" }
forge-gradle = { id = "net.minecraftforge.gradle", version.ref = "plugin_forge_gradle" }
forge-jarjar = { id = "net.minecraftforge.jarjar", version.ref = "plugin_forge_jarjar" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "plugin_neoforge_moddev" }

[bundles]
cats = ["cats-kernel", "cats-core", "cats-free"]
