modLoader = "kotori_scala"
loaderVersion = "[1.0.0,)"
license = "ALL RIGHTS RESERVED"
[[mods]]
modId = "slp_examples"
version = "1.0.0"
displayName = "SLP Examples"
authors = "Kotori316"
description = "Examples of SLP"
[[dependencies.slp_examples]]
modId = "forge"
mandatory = true
versionRange = "[64.0.0, 65)"
ordering = "NONE"
side = "BOTH"
[[dependencies.slp_examples]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1.0, 26.2.0)"
ordering = "NONE"
side = "BOTH"
