modLoader = "kotori_scala"
loaderVersion = "[1.0.0,)"
license = "ALL RIGHTS RESERVED"
[[mods]]
modId = "slp_examples"
version = "1.0.0"
displayName = "SLP Examples"
authors = "Kotori316"
description = "Examples of SLP"
[[dependencies.slp_examples]]
modId = "neoforge"
mandatory = true
versionRange = "[26.2.0.7-beta, 26.3.0.0)"
ordering = "NONE"
side = "BOTH"
[[dependencies.slp_examples]]
modId = "minecraft"
mandatory = true
versionRange = "[26.2.0, 26.3.0)"
ordering = "NONE"
side = "BOTH"
