name: Build Test

on:
  push:
    branches:
      - "1.20"
    tags:
      - "!*"

jobs:
  check-forge:
    runs-on: ubuntu-latest
    env:
      DISABLE_NEO_FORGE: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew data
      - run: ./gradlew test build
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: '*/build/libs/*'
          name: ${{ github.event.repository.name }}-Forge-${{ github.run_number }}
          retention-days: 3

  check-neoforge:
    runs-on: ubuntu-latest
    env:
      DISABLE_FORGE: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew data
      - run: ./gradlew test build
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: '*/build/libs/*'
          name: ${{ github.event.repository.name }}-NeoForge-${{ github.run_number }}
          retention-days: 3
