name: Build Test

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Precompile
        run: chmod +x ./gradlew && ./gradlew compileScala --continue --warning-mode all --info
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Test
        run: chmod +x ./gradlew && ./gradlew test --info
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
