name: Build Test

on:
  push:
    branches:
      - "1.20.5"
    tags:
      - "!*"
  pull_request:
    branches:
      - "1.20.5"

jobs:
  check-forge:
    runs-on: ubuntu-latest
    if: false
    env:
      DISABLE_NEO_FORGE: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew data
      - run: ./gradlew test build
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-Forge-${{ github.run_number }}'
          retention-days: 3

  check-neoforge:
    runs-on: ubuntu-latest
    env:
      DISABLE_FORGE: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew data
      - run: ./gradlew test build
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-NeoForge-${{ github.run_number }}'
          retention-days: 3
