name: Build Test

on:
  push:
    branches:
      - "26.1"
    tags:
      - "!*"
  pull_request:
    branches:
      - "26.1"

jobs:
  check-forge:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 100
    env:
      DISABLE_NEO_FORGE: 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - run: ./gradlew data checkReleaseVersion
      - run: ./gradlew test build publishToMavenLocal --scan
      - name: Prepare example runs
        run: |
          set -eux
          for d in example/*; do
            mkdir -p "$d/run"
          done
          ls example/*
      - name: Check examples
        run: ./gradlew runGameTestServer --stacktrace || ./gradlew runGameTestServer --stacktrace
      - name: Check examples with runData
        run: ./gradlew runData --stacktrace || ./gradlew runData --stacktrace
      - name: Publish
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-Forge-${{ github.run_number }}'
          retention-days: 3

  check-neoforge:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    env:
      DISABLE_FORGE: 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set executable
        run: chmod +x ./gradlew
      - name: Set memory
        run: |
          cat <<EOF >> gradle.properties
          # CI Memory Settings
          org.gradle.daemon=false
          org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
          org.gradle.parallel=false
          org.gradle.workers.max=2
          EOF
      - name: Get cache
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - run: ./gradlew data checkReleaseVersion --stacktrace
      - run: ./gradlew test build publishToMavenLocal --scan
      - name: Prepare example runs
        run: |
          set -eux
          for d in example/*; do
            mkdir -p "$d/run"
          done
          ls example/*
      - name: Check examples
        run: ./gradlew runGameTestServer --stacktrace || ./gradlew runGameTestServer --stacktrace
      - name: Publish
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-NeoForge-${{ github.run_number }}'
          retention-days: 3
