name: Build Test

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  debug_log:
    runs-on: ubuntu-latest
    step:
      - name: Check Branch name
        run: echo "${{ github.event.base_ref }}"
      - name: OS name
        run: echo "${{ runner.os }}"
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11]
        # test against some forge versions including recommend version.
        #forge: [ 1.16.3-34.1.0, 1.16.4-35.0.2, fixed ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/forge_gradle/assets
          key: ${{ runner.os }}-${{ github.event.base_ref }}
      - name: Check Dependency
        run: chmod +x ./gradlew && ./gradlew data --no-daemon
      - name: download_assets
        run: |
          chmod +x ./gradlew
          ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
        continue-on-error: true
      - name: Test JUnit
        run: chmod +x ./gradlew && ./gradlew test --no-daemon --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Test runData
        run: chmod +x ./gradlew && ./gradlew runData --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Check started and errored
        run: |
          [ -f test_started.txt ]
          ! [ -f error-trace.txt ]
      - id: show-failure-log
        if: failure()
        run: cat error-trace.txt
