name: Build Test

on:
  push:
    branches:
      - "26.1"
    tags:
      - "!*"
  pull_request:
    branches:
      - "26.1"

jobs:
  check-forge:
    strategy:
      matrix:
        os: ${{ github.event_name == 'pull_request' && fromJSON('["ubuntu-24.04-arm"]') || fromJSON('["ubuntu-24.04-arm", "ubuntu-latest", "windows-latest"]') }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 100
    env:
      DISABLE_NEO_FORGE: 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: Get cache
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - run: ./gradlew data checkReleaseVersion
      - run: ./gradlew test build publishToMavenLocal checkBinaryContent --scan
        env:
          DISABLE_EXAMPLE: true
      - name: Prepare example runs
        shell: bash
        run: |
          set -eux
          for d in example/*; do
            mkdir -p "$d/run"
          done
          ls example/*
      - name: Check examples
        run: ./gradlew runGameTestServer --stacktrace || ./gradlew runGameTestServer --stacktrace
      - name: Check examples with runData
        run: ./gradlew runData --stacktrace || ./gradlew runData --stacktrace
      - name: Publish
        if: ${{ matrix.os == 'ubuntu-24.04-arm' && github.event_name == 'push' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-Forge-${{ github.run_number }}'
          retention-days: 3

  check-neoforge:
    strategy:
      matrix:
        os: ${{ github.event_name == 'pull_request' && fromJSON('["ubuntu-24.04-arm"]') || fromJSON('["ubuntu-24.04-arm", "ubuntu-latest", "windows-latest"]') }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 100
    env:
      DISABLE_FORGE: 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: Set memory
        shell: bash
        run: |
          cat <<EOF >> gradle.properties
          # CI Memory Settings
          org.gradle.daemon=false
          org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
          org.gradle.parallel=false
          org.gradle.workers.max=2
          EOF
      - name: Get cache
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - run: ./gradlew data checkReleaseVersion --stacktrace
      - run: ./gradlew test build publishToMavenLocal checkBinaryContent --scan
        env:
          DISABLE_EXAMPLE: true
      - name: Prepare example runs
        shell: bash
        run: |
          set -eux
          for d in example/*; do
            mkdir -p "$d/run"
          done
          ls example/*
      - name: Check examples
        run: ./gradlew runGameTestServer --stacktrace || ./gradlew runGameTestServer --stacktrace
      - name: Publish
        if: ${{ matrix.os == 'ubuntu-24.04-arm' && github.event_name == 'push' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: '*/build/libs/*'
          name: '${{ github.event.repository.name }}-NeoForge-${{ github.run_number }}'
          retention-days: 3
