name: Build Test

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Test
        run: chmod +x ./gradlew && ./gradlew test --info --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
