name: PullRequest Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Compile and Test
        run: gradle compileScala test --continue --info
